"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, BarChart3, Clock3, FileText, Flame, Lightbulb, Play, Quote, Sparkles, Target } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Session = { id: string | number; created_at: string; duration_seconds: number | null; elapsed_duration_seconds: number | null; speaking_duration_seconds: number | null; topic: string | null; transcript: string | null; feedback: unknown };
type Skill = "clarity" | "structure" | "fluency" | "confidence";
const skillKeys: Skill[] = ["clarity", "structure", "fluency", "confidence"];
const asRecord = (value: unknown): Record<string, unknown> => value && typeof value === "object" ? value as Record<string, unknown> : {};
const average = (values: Array<number | null>) => { const usable = values.filter((value): value is number => value !== null); return usable.length ? usable.reduce((sum, value) => sum + value, 0) / usable.length : null; };
const score = (feedback: unknown, skill: Skill) => { const value = asRecord(asRecord(feedback)[skill]).score; return typeof value === "number" ? Math.round(value <= 10 ? value * 10 : Math.min(value, 100)) : null; };
const duration = (session: Session) => session.elapsed_duration_seconds ?? session.speaking_duration_seconds ?? session.duration_seconds ?? 0;
const time = (seconds: number) => { const mins = Math.round(seconds / 60); return mins >= 60 ? `${Math.floor(mins / 60)}h${mins % 60 ? ` ${mins % 60}m` : ""}` : `${Math.max(0, mins)}m`; };
const sessionTitle = (session: Session) => { if (session.topic?.trim()) return session.topic.trim(); const text = (session.transcript ?? "").replace(/\s+/g, " ").trim(); return text ? `${text.slice(0, 58).trimEnd()}${text.length > 58 ? "…" : ""}` : "Practice session"; };

export default function DashboardPage() {
  const [sessions, setSessions] = useState<Session[]>([]); const [fullName, setFullName] = useState<string | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const load = async () => { setState("loading"); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setState("error"); return; } const [profile, sessionData] = await Promise.all([supabase.from("profiles").select("full_name").eq("id", user.id).maybeSingle(), supabase.from("sessions").select("id, created_at, duration_seconds, elapsed_duration_seconds, speaking_duration_seconds, topic, transcript, feedback").eq("user_id", user.id).order("created_at", { ascending: false })]); if (sessionData.error) { setState("error"); return; } const name = profile.data?.full_name; setFullName(typeof name === "string" && name.trim() ? name.trim() : null); setSessions((sessionData.data as Session[]) ?? []); setState("ready"); };
  useEffect(() => { void Promise.resolve().then(load); }, []);
  const info = useMemo(() => {
    const perSkill = skillKeys.map((skill) => ({ skill, value: average(sessions.map((item) => score(item.feedback, skill))) }));
    const scores = sessions.map((item) => average(skillKeys.map((skill) => score(item.feedback, skill)))); const mean = average(scores); const chronological = [...scores].reverse().filter((item): item is number => item !== null); const change = chronological.length > 1 && mean !== null ? Math.round(mean - chronological[0]) : null;
    const focus = sessions.length >= 2 ? perSkill.filter((item): item is { skill: Skill; value: number } => item.value !== null).sort((a, b) => a.value - b.value)[0] ?? null : null;
    const monday = new Date(); monday.setHours(0, 0, 0, 0); monday.setDate(monday.getDate() - ((monday.getDay() + 6) % 7)); const thisWeek = sessions.filter((item) => new Date(item.created_at) >= monday); const total = sessions.reduce((sum, item) => sum + duration(item), 0); const weekTime = thisWeek.reduce((sum, item) => sum + duration(item), 0);
    const practiced = new Set(sessions.map((item) => new Date(item.created_at).toLocaleDateString("en-CA"))); const cursor = new Date(); cursor.setHours(0, 0, 0, 0); if (!practiced.has(cursor.toLocaleDateString("en-CA"))) cursor.setDate(cursor.getDate() - 1); let streak = 0; while (practiced.has(cursor.toLocaleDateString("en-CA"))) { streak += 1; cursor.setDate(cursor.getDate() - 1); }
    const week = Array.from({ length: 7 }, (_, index) => { const day = new Date(monday); day.setDate(monday.getDate() + index); return { key: day.toISOString(), label: day.toLocaleDateString(undefined, { weekday: "short" }).slice(0, 1), active: practiced.has(day.toLocaleDateString("en-CA")) }; });
    return { perSkill, mean, change, focus, thisWeek: thisWeek.length, total, weekTime, streak, week };
  }, [sessions]);
  if (state === "loading") return <Skeleton />;
  if (state === "error") return <main className="grid min-h-full place-items-center bg-[#fcfcfd]"><div className="rounded-2xl border border-[#e9e7ef] bg-white p-8 text-center"><p className="font-semibold text-[#171722]">Couldn&apos;t load your practice data.</p><button onClick={() => void load()} className="mt-4 rounded-lg bg-[#7b68d8] px-4 py-2 text-sm text-white">Try again</button></div></main>;
  const hour = new Date().getHours(); const name = fullName ?? "Learner"; const focusName = info.focus ? info.focus.skill[0].toUpperCase() + info.focus.skill.slice(1) : "Discovering";
  return <main className="min-h-full bg-[#fcfcfd] px-5 py-5 text-[#171722] sm:px-8 lg:px-10"><div className="mx-auto max-w-[1230px] space-y-4">
    <header className="grid items-center gap-5 lg:grid-cols-[.88fr_1.12fr]"><div className="pl-1"><p className="text-[19px] text-[#4f6088]">{hour < 12 ? "Good morning," : hour < 18 ? "Good afternoon," : "Good evening,"}</p><h1 className="mt-1 text-[48px] font-semibold leading-none tracking-[-.065em] text-[#10162e] sm:text-[58px]">{name} <span className="text-[var(--theme-primary)] [text-shadow:2px_2px_0_var(--theme-accent)]">✦</span></h1><p className="mt-6 max-w-[420px] text-[18px] leading-7 text-[#607099]">A little practice today goes a long way<br className="hidden xl:block" /> in building a more confident you.</p>{!fullName && <Link href="/settings" className="mt-2 inline-block text-[11px] text-[#858aa0]">Add your name in Settings to personalize Aynam.</Link>}</div><section className="relative h-[235px] overflow-hidden rounded-[20px] border border-[#e5e0fa] bg-[#f3f0ff] px-14 py-12 shadow-[0_8px_22px_rgba(100,83,173,.06)]"><div className="absolute -right-12 top-4 h-56 w-56 rounded-t-[100px] bg-gradient-to-b from-[var(--theme-accent-soft)] to-[var(--theme-surface)] opacity-90" /><div className="absolute bottom-0 right-0 h-16 w-[52%] rounded-tl-[100%] bg-[var(--theme-accent-soft)] opacity-80" /><div className="absolute bottom-6 right-28 h-16 w-3 rounded-t-full bg-[var(--theme-primary)]" /><div className="absolute bottom-18 right-[104px] h-12 w-12 rounded-full border-2 border-[var(--theme-accent)] bg-[var(--theme-surface-elevated)]" /><div className="relative z-10"><p className="text-[10px] font-semibold tracking-[.18em] text-[#6065a1]">SMALL STEPS, BIG CHANGE</p><h2 className="mt-4 text-[29px] font-medium leading-9 tracking-[-.04em] text-[#25335c]">Better conversations<br />start with you.</h2><Link href="/practice" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[var(--theme-primary)] px-5 py-3 text-[13px] font-medium !text-[var(--theme-surface)] shadow-[0_6px_15px_rgba(103,6,38,.22)]">Start practicing <ArrowRight className="h-4 w-4 !text-[var(--theme-surface)]" /></Link></div></section></header>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat icon={<BarChart3 />} label="Total sessions" value={String(sessions.length)} note={sessions.length ? info.thisWeek ? `↑ +${info.thisWeek} this week` : "No sessions this week." : "Your first session is waiting."} /><Stat icon={<Sparkles />} label="Avg. score" value={info.mean === null ? "—" : `${Math.round(info.mean)} /100`} note={info.change === null ? sessions.length ? "Your baseline" : "Your baseline appears after your first session." : `${info.change >= 0 ? "↑ +" : "↓ "}${Math.abs(info.change)} since first session`} /><Stat icon={<Clock3 />} label="Total practice time" value={time(info.total)} note={info.weekTime ? `↑ +${time(info.weekTime)} this week` : sessions.length ? "Keep practicing." : "Start your first session."} /><Stat icon={<Target />} label="Current focus" value={focusName} note={info.focus ? `Make your ${info.focus.skill} more natural and continuous.` : "Complete a few sessions to find your focus."} /></section>
    <section className="grid gap-3 lg:grid-cols-[1.2fr_.9fr_.8fr]"><Panel icon={<Play />} title="Your next practice" subtitle="Based on your recent sessions" className="bg-gradient-to-br from-[#fffdfc] to-[#fff9f1]"><div className="mt-5 flex items-center gap-4"><IconBox><FileText className="h-5 w-5" /></IconBox><div className="min-w-0"><h3 className="text-[15px] font-semibold">{info.focus ? `Build stronger ${info.focus.skill}.` : "Tell me about something you’re passionate about."}</h3><p className="mt-1 text-[12px] leading-4 text-[#68779b]">Practice a 2-minute answer with a clear beginning, middle, and close.</p><div className="mt-2 flex gap-2"><Tag>{info.focus ? focusName : "Starter"}</Tag><Tag>2 min</Tag></div></div><Link href="/practice" className="ml-auto inline-flex shrink-0 items-center gap-2 rounded-lg bg-[var(--theme-primary)] px-4 py-2.5 text-[12px] font-medium !text-[var(--theme-surface)]">Start <ArrowRight className="h-3.5 w-3.5 !text-[var(--theme-surface)]" /></Link></div></Panel><Panel icon={<Flame className="text-[#ef952e]" />} title="Your streak"><div className="mt-5 flex justify-between">{info.week.map((day) => <div key={day.key} className="text-center"><span className={`mx-auto grid h-6 w-6 place-items-center rounded-full text-[10px] ${day.active ? "bg-[var(--theme-accent)] text-[var(--theme-primary)] shadow-sm" : "bg-[#f2f2f5] text-[#afb0bc]"}`}>{day.active ? "✓" : "•"}</span><span className="mt-1.5 block text-[9px] text-[#74809d]">{day.label}</span></div>)}</div><p className="mt-5 text-[20px] font-semibold tracking-[-.04em]">{info.streak ? `${info.streak} day streak` : "Start your streak"}</p><p className="mt-1 text-[11px] text-[#68779b]">{sessions.length ? "Keep going. Consistency builds confidence." : "Your first session starts your streak."}</p></Panel><Panel icon={<Quote />} title="A little reminder" className="relative overflow-hidden bg-[#f5f2ff]"><div className="absolute -bottom-7 -right-4 h-20 w-60 rounded-[100%] bg-[var(--theme-accent-soft)]" /><p className="relative mt-6 text-center text-[18px] font-medium leading-6 tracking-[-.035em] text-[#28345d]">“Clearer communication<br />creates a clearer you.”</p><p className="relative mt-3 text-center text-[11px] text-[#727ca2]">— Aynam</p></Panel></section>
    <section className="grid gap-3 lg:grid-cols-[1.05fr_.92fr_.75fr]"><Panel icon={<Clock3 />} title="Recent sessions" link="/history" linkText="View all">{sessions.length ? <div className="mt-2 divide-y divide-[#efedf3]">{sessions.slice(0, 3).map((session) => { const value = average(skillKeys.map((key) => score(session.feedback, key))); return <Link href="/history" key={session.id} className="flex items-center gap-3 py-2.5"><IconBox><FileText className="h-4 w-4" /></IconBox><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium">{sessionTitle(session)}</p><p className="mt-0.5 text-[11px] text-[#74809d]">{new Date(session.created_at).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" })} · {time(duration(session))}</p></div><span className="rounded-full bg-[#f1eeff] px-2 py-1 text-[11px] font-medium text-[#7059c6]">{value === null ? "—" : Math.round(value)}</span><ArrowRight className="h-3.5 w-3.5 text-[#808bac]" /></Link>; })}</div> : <Empty text="Your practice history will appear here." />}</Panel><Panel icon={<BarChart3 />} title="Insights snapshot" link="/insights" linkText="View insights">{info.perSkill.some((item) => item.value !== null) ? <div className="mt-5 space-y-4">{info.perSkill.map((item) => <div key={item.skill} className="grid grid-cols-[68px_1fr_26px] items-center gap-2 text-[11px]"><span className="capitalize">{item.skill}</span><span className="h-2 overflow-hidden rounded-full bg-[var(--theme-accent-soft)]"><span className="block h-full rounded-full bg-[var(--theme-accent)]" style={{ width: `${item.value ?? 0}%` }} /></span><span className="text-right">{item.value === null ? "—" : Math.round(item.value)}</span></div>)}</div> : <Empty text="Your communication profile is waiting. Complete a few sessions and Aynam will start learning your patterns." />}</Panel><Panel icon={<Lightbulb />} title="Today’s tip"><p className="mt-5 text-center text-[17px] font-medium leading-6">Pause for a second<br />before you answer.</p><p className="mt-3 text-center text-[11px] leading-4 text-[#74809d]">A short pause helps you organize your thoughts and sound more confident.</p><Link href="/practice" className="mt-4 flex items-center justify-center gap-2 rounded-lg bg-[var(--theme-accent-soft)] px-3 py-2.5 text-[12px] font-medium text-[var(--theme-primary)]">Try it in your next session <ArrowRight className="h-3.5 w-3.5" /></Link></Panel></section>
  </div></main>;
}

function IconBox({ children }: { children: React.ReactNode }) { return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--theme-accent-soft)] text-[var(--theme-primary)]">{children}</span>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-[var(--theme-accent-soft)] px-2.5 py-1 text-[10px] text-[var(--theme-primary)]">{children}</span>; }
function Stat({ icon, label, value, note }: { icon: React.ReactNode; label: string; value: string; note: string }) { return <section className="min-w-0 rounded-[18px] border border-[#e9e7ef] bg-white px-4 py-3.5 shadow-[0_4px_14px_rgba(67,54,118,.025)]"><div className="flex items-center gap-3"><IconBox>{icon}</IconBox><p className="text-[13px] font-medium text-[#3f4a70]">{label}</p></div><p className="mt-2 text-[27px] font-semibold leading-none tracking-[-.055em] text-[#141a34]">{value}</p><p className="mt-2 min-h-3 text-[11px] text-[var(--theme-accent)]">{note}</p></section>; }
function Panel({ icon, title, subtitle, link, linkText, className = "bg-white", children }: { icon: React.ReactNode; title: string; subtitle?: string; link?: string; linkText?: string; className?: string; children: React.ReactNode }) { return <section className={`min-h-[190px] rounded-[18px] border border-[#e9e7ef] p-4 shadow-[0_4px_14px_rgba(67,54,118,.025)] ${className}`}><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-3"><IconBox>{icon}</IconBox><div><h2 className="text-[15px] font-semibold tracking-[-.025em]">{title}</h2>{subtitle && <p className="mt-0.5 text-[11px] text-[#74809d]">{subtitle}</p>}</div></div>{link && <Link href={link} className="flex items-center gap-1 text-[11px] text-[#6b78a1]">{linkText} <ArrowRight className="h-3 w-3" /></Link>}</div>{children}</section>; }
function Empty({ text }: { text: string }) { return <div className="mt-6 text-center"><p className="text-[13px] font-medium">No sessions yet.</p><p className="mx-auto mt-1 max-w-[250px] text-[11px] leading-4 text-[#74809d]">{text}</p><Link href="/practice" className="mt-3 inline-flex items-center gap-1 text-[11px] font-medium text-[#745cf0]">Start practicing <ArrowRight className="h-3 w-3" /></Link></div>; }
function Skeleton() { return <main className="min-h-full bg-[#fcfcfd] p-8"><div className="mx-auto max-w-[1230px] animate-pulse space-y-4"><div className="grid gap-5 lg:grid-cols-2"><div className="h-[235px] rounded-[20px] bg-[#f1eff5]" /><div className="h-[235px] rounded-[20px] bg-[#f1effb]" /></div><div className="grid grid-cols-4 gap-3">{[0, 1, 2, 3].map((item) => <div key={item} className="h-[125px] rounded-[18px] bg-[#f1eff5]" />)}</div><div className="h-[190px] rounded-[18px] bg-[#f1eff5]" /></div></main>; }
